spring.application.name=agendamento

# Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/perolanegra_db
spring.datasource.username=postgres
spring.datasource.password=0306

# Configurações do Hibernate/JPA
# O "update" faz com que o Spring crie/atualize as tabelas automaticamente baseado nos seus Models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true